version: "2"

services:

  orderer0:
    extends:
      file: docker-compose-orderer-solo.yml
      service: orderer0


  peer0:
    extends:
      file: docker-compose-next.yml
      service: vpNext
    environment:
      - CORE_PEER_ID=vp0
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:7050
      - CORE_PEER_MSPCONFIGPATH=${PEER0_CORE_PEER_MSPCFGPATH}
    depends_on:
      - orderer0
    # ports:
    #   - 7050:6060


  peer1:
    extends:
      file: docker-compose-next.yml
      service: vpNext
    environment:
      - CORE_PEER_ID=vp1
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0:7051
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:7050
      - CORE_PEER_MSPCONFIGPATH=${PEER1_CORE_PEER_MSPCFGPATH}
    depends_on:
      - orderer0
      - peer0

  peer2:
    extends:
      file: docker-compose-next.yml
      service: vpNext
    environment:
      - CORE_PEER_ID=vp2
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0:7051
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:7050
      - CORE_PEER_MSPCONFIGPATH=${PEER2_CORE_PEER_MSPCFGPATH}
    depends_on:
      - orderer0
      - peer0

  peer3:
    extends:
      file: docker-compose-next.yml
      service: vpNext
    environment:
      - CORE_PEER_ID=vp3
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0:7051
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer0:7050
      - CORE_PEER_MSPCONFIGPATH=${PEER3_CORE_PEER_MSPCFGPATH}
    depends_on:
      - orderer0
      - peer0
