version: "2"

services:

    ordererBase:
        image: hyperledger/fabric-orderer
        environment:
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LOGLEVEL=debug
            - ORDERER_GENERAL_GENESISMETHOD=${ORDERER_GENERAL_GENESISMETHOD}
            - ORDERER_GENERAL_GENESISFILE=${ORDERER_GENERAL_GENESISFILE}
        volumes:
            - ./volumes/orderer:/var/hyperledger/bddtests/volumes/orderer
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
        command: orderer
        ports:
          - '7050'

volumes:

    orderer:
