version: '2'
networks:
   bridge:

services:
  orderer:
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LEDGERTYPE=ram
      - ORDERER_GENERAL_BATCHTIMEOUT=10s
      - ORDERER_GENERAL_BATCHSIZE_MAXMESSAGECOUNT=2
      - ORDERER_GENERAL_MAXWINDOWSIZE=1000
      - ORDERER_GENERAL_ORDERERTYPE=solo
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_RAMLEDGER_HISTORY_SIZE=100
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    networks:
      - bridge


  vpserv:
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_NETWORKID=${CORE_PEER_NETWORKID}
      - CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_COMMITTER_ENABLED=true
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer:7050
    volumes:
        - /var/run/:/host/var/run/
    networks:
      - bridge

  vp0:
    extends:
      service: vpserv
    environment:
      - CORE_PEER_ID=vp0
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_ORGLEADER=true
    ports:
      - 7051:7051
      - 7053:7053
    command: peer node start
    links:
      - orderer

  vp1:
    extends:
      service: vpserv
    environment:
      - CORE_PEER_ID=vp1
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_GOSSIP_BOOTSTRAP=vp0:7051
      - CORE_PEER_GOSSIP_ORGLEADER=false
    command: peer node start
    links:
      - orderer

  vp2:
    extends:
      service: vpserv
    environment:
      - CORE_PEER_ID=vp2
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer:7050
      - CORE_PEER_GOSSIP_BOOTSTRAP=vp0:10000
      - CORE_PEER_GOSSIP_ORGLEADER=false
    command: peer node start
    links:
      - orderer

